export type VerdictType = 'True' | 'False' | 'Unverified' | 'Misleading';

export interface Citation {
  title: string;
  url: string;
}

export interface VerificationResult {
  verdict: VerdictType;
  confidence: number;
  explanation: string;
  citations: Citation[];
  category: 'Medical' | 'Financial' | 'Political' | 'Other';
  summary?: string; // Generated by the secondary model
}

export type ViewState = 'home' | 'text' | 'screenshot' | 'demo' | 'sources';

export const DEMO_EXAMPLES = [
  {
    id: 'rbi',
    title: 'Fake RBI Note',
    text: 'RBI has issued a new notification that 2000 rupee notes will verify GPS location and send data to the government.'
  },
  {
    id: 'trains',
    title: 'Mumbai Trains Update',
    text: 'Western Railway has announced a mega block on Sunday between Borivali and Goregaon for bridge maintenance.'
  },
  {
    id: 'cow',
    title: 'Cow Urine Claim',
    text: 'Drinking fresh cow urine every morning cures cancer and diabetes within 3 months according to new WHO study.'
  }
];